version: "3.8"

services:
  nginx:
    networks:
      - InceptionNetwork
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    volumes:
      - wp_data:/var/www/html/wordpress
    ports:
      - "443:443"
    restart: always

  mariadb:
    networks:
      - InceptionNetwork
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  wordpress:
    networks:
      - InceptionNetwork
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    env_file: .env
    volumes:
      - wp_data:/var/www/html/wordpress
    depends_on:
      - mariadb
      - nginx
    restart: always

networks:
  InceptionNetwork:
    driver: bridge

volumes:
  db_data:
    driver_opts:
      o: bind
      type: none
      device: /home/nettalha/data/db
  wp_data:
    driver_opts:
      o: bind
      type: none
      device: /home/nettalha/data/wp