version: "3.8"

services:
  nginx:
    networks:
      - InceptionNetwork
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    volumes:
      - wp_data:/var/www/html/wordpress
    ports:
      - "443:443"
    restart: always

  mariadb:
    networks:
      - InceptionNetwork
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    env_file: .env
    # environment:
      # MYSQL_DATABASE: ${DB_NAME}
      # MYSQL_USER: ${DB_USER}
      # MYSQL_PASSWORD: ${DB_PASSWD}
      # MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWD}
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  wordpress:
    networks:
      - InceptionNetwork
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    env_file: .env
    volumes:
      - wp_data:/var/www/html/wordpress
    # environment:
      # WP_HOST: mariadb
      # WP_TITLE: ${WP_TITLE}
      # WP_URL: ${WP_URL}
      # WP_ADMIN: ${WP_ADMIN}
      # WP_ADMIN_PASSWD: ${WP_ADMIN_PASSWD}
      # WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      # WP_USER_EMAIL: ${WP_USER_EMAIL}
      # WP_DB_NAME: ${DB_NAME}
      # DB_USER: ${DB_USER}
      # WP_USER: ${WP_USER}
      # WP_PASSWD: ${WP_PASSWD}
      # DB_PASSWD: ${DB_PASSWD}
      # DB_ROOT_PASSWD: ${DB_ROOT_PASSWD}
    depends_on:
      - mariadb
      - nginx
    restart: always

networks:
  InceptionNetwork:
    driver: bridge

volumes:
  db_data:
    driver_opts:
      o: bind
      type: none
      device: /home/nettalha/data/db
  wp_data:
    driver_opts:
      o: bind
      type: none
      device: /home/nettalha/data/wp